"""Job-related models and factory helpers for storing work items.

This module declares the job lifecycle states and provides a helper to
construct a new job document with consistent audit fields. Keeping this in a
shared location ensures all services use the same field names and status
values.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Optional


class JobStatus(str, Enum):
    """Possible states for a video processing job.

    enum values to understand the state of a job in the pipeline.
    These are used to track progress.
    """
    PENDING      = "pending" # job has been queued but not yet started
    DOWNLOADING  = "downloading" # downloader is actively fetching the video
    DOWNLOADED   = "downloaded" # all required file were downloaded and captured
    PROCESSING   = "processing" #transcription/parsing is in progress
    TRANSCRIBED  = "transcribed" # transcription completed successfully
    FAILED       = "failed" # job failed at some stage due to a genuine error (network, missing file, bad transcode, ...) — retried up to JOB_MAX_RETRIES, then re-queued from scratch if the scraper rediscovers it. This is the status to check when triaging problems.
    EXCLUDED     = "excluded" # job was deliberately not processed because of a business rule (see failed_stage/error for which one) — e.g. too short to bother transcribing, or a live-channel entry with no stable recording. Not an error and not retried/re-queued; the decision won't change on rediscovery.


def new_video_job(video_url: str, source: str, metadata: Optional[dict] = None) -> dict:
    """Creates a job document for inserting into MongoDB.

    Args:
        video_url: Canonical URL used to identify and download the video.
        source: Short source name (must match detectors/portal registry).
        metadata: Optional portal-provided metadata; avoid using mutable
                  default arguments by passing None.

    Returns:
        A dict ready to upsert into the jobs collection.
    """
    # avoid mutable default argument
    if metadata is None:
        metadata = {}

    # _id being auto-generated by MongoDB, so we don't set it here. The database will assign a unique ObjectId when the document is inserted.
    return {
        "video_url":      video_url, # url of video to download
        "captioned":      metadata.get("captioned", False), # whether the video has captions
        "source":         source, # original source of the video (e.g. "michigan_house")
        "status":         JobStatus.PENDING, # initial state when queued
        "metadata":       metadata, # portal-specific metadata (title, duration, etc.)
        "retries":        0, # number of retry attempts at the current stage
        "error":          None, # last error message, if any
        "created_at":     datetime.now(timezone.utc),
        "updated_at":     datetime.now(timezone.utc),
        "downloaded_at":  None, # set when downloads succeed
        "transcribed_at": None, # set when transcription completes
    }